In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer,StandardScaler
from sklearn.metrics import accuracy_score ,precision_score,recall_score, f1_score

In [ ]:
df = pd.read_csv("/content/sample_data/heart.csv")

In [ ]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
df.info()
df.isnull().sum()
print("no. of duplicates: ",df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB
no. of duplicates:  1

In [ ]:
df.drop_duplicates(inplace=True)
print("no. of duplicates: ",df.duplicated().sum())

no. of duplicates:  0

In [ ]:
x=df.iloc[:,:13]
y=df.iloc[:,13]
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
b = np.ones((x.shape[0], 1))
x= np.hstack((x, b))
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,shuffle = True)

In [ ]:
#generating the weights+bias
weights=np.random.rand(14,14)

(241, 14)

In [ ]:
# wtranspose x
w_transpose_x=np.dot(weights, x_train.T);
def sigmoid(x):
  return 1/(1 + np.e**-x)

y_pred=sigmoid(w_transpose_x)
print(y_pred.shape)

(14, 241)

In [ ]:
def train(epochs,weights,x_train,y_pred,y_train,learning_rate):
  for i in range(epochs):
    for j in range(len(weights)):
      ys=(y_pred[j]-y_train)
      change=1/241*(learning_rate *np.dot(x_train.T,ys))
      weights[j]=weights[j]-change
  return weights

weights=train(200,weights,x_train,y_pred,y_train,0.1)

In [ ]:
def test(weights,x_test):
  predictions=[]
  y_pred=np.dot(weights,x_test.T)
  y_pred=sigmoid(y_pred)
  return y_pred

y_predict=test(weights,x_test)
for i in range(len(y_predict)):
  for j in range(len(y_predict[i])):
    if y_predict[i][j]<=0.5:
      y_predict[i][j]=0
    else:
      y_predict[i][j]=1

max_index=0
max_accuracy=-1
for k in range(len(y_predict)):
  if(accuracy_score(y_predict[i],y_test) > max_accuracy):
    max_accuracy=accuracy_score(y_predict[i],y_test)
    max_index=k

print("The accuracy is: ",accuracy_score(y_test,y_predict[max_index]))
print("The precision is: ",precision_score(y_test,y_predict[max_index]))
print("Recall is: ",recall_score(y_test,y_predict[max_index]))
print('F1-score:', f1_score(y_test,y_predict[max_index]))

The accuracy is:  0.8524590163934426
The precision is:  0.8709677419354839
Recall is:  0.84375
F1-score: 0.8571428571428571